// Mocks generated by Mockito 5.4.6 from annotations
// in veggie_cart/test/views/gardeners_page_content_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:au_bio_jardin_app/models/user_model.dart' as _i3;
import 'package:au_bio_jardin_app/repositories/account_repository.dart' as _i2;
import 'package:au_bio_jardin_app/viewmodels/account_view_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountRepository_0 extends _i1.SmartFake
    implements _i2.AccountRepository {
  _FakeAccountRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountViewModel extends _i1.Mock implements _i4.AccountViewModel {
  MockAccountViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get accountRepository =>
      (super.noSuchMethod(
            Invocation.getter(#accountRepository),
            returnValue: _FakeAccountRepository_0(
              this,
              Invocation.getter(#accountRepository),
            ),
          )
          as _i2.AccountRepository);

  @override
  _i3.UserModel get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeUserModel_1(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i3.UserModel);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get confirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPassword),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#confirmPassword),
            ),
          )
          as String);

  @override
  bool get showSignInForm =>
      (super.noSuchMethod(
            Invocation.getter(#showSignInForm),
            returnValue: false,
          )
          as bool);

  @override
  bool get showSignUpForm =>
      (super.noSuchMethod(
            Invocation.getter(#showSignUpForm),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Stream<List<_i3.UserModel>> get gardenersStream =>
      (super.noSuchMethod(
            Invocation.getter(#gardenersStream),
            returnValue: _i6.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i6.Stream<List<_i3.UserModel>>);

  @override
  set currentUser(_i3.UserModel? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set password(String? value) => super.noSuchMethod(
    Invocation.setter(#password, value),
    returnValueForMissingStub: null,
  );

  @override
  set confirmPassword(String? value) => super.noSuchMethod(
    Invocation.setter(#confirmPassword, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignInForm(bool? value) => super.noSuchMethod(
    Invocation.setter(#showSignInForm, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignUpForm(bool? value) => super.noSuchMethod(
    Invocation.setter(#showSignUpForm, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleSignInForm() => super.noSuchMethod(
    Invocation.method(#toggleSignInForm, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSignUpForm() => super.noSuchMethod(
    Invocation.method(#toggleSignUpForm, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signOut(_i7.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearUserData() => super.noSuchMethod(
    Invocation.method(#clearUserData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> signIn(_i7.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signUp(_i7.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleGardenerStatus(
    _i7.BuildContext? context,
    _i3.UserModel? user,
    bool? isGardener,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleGardenerStatus, [
              context,
              user,
              isGardener,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.UserModel>> searchCustomers(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#searchCustomers, [name]),
            returnValue: _i6.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i6.Future<List<_i3.UserModel>>);

  @override
  _i6.Future<void> promoteToGardener(
    _i7.BuildContext? context,
    _i3.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#promoteToGardener, [context, user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> updateUserProfile(
    _i7.BuildContext? context,
    _i3.UserModel? updatedUser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [context, updatedUser]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isPasswordValid(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#isPasswordValid, [password]),
            returnValue: false,
          )
          as bool);

  @override
  bool isEmailValid(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailValid, [email]),
            returnValue: false,
          )
          as bool);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
