// Mocks generated by Mockito 5.4.6 from annotations
// in au_bio_jardin_app/test/viewmodels/account_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:au_bio_jardin_app/models/user_model.dart' as _i7;
import 'package:au_bio_jardin_app/repositories/account_repository.dart' as _i5;
import 'package:au_bio_jardin_app/services/auth_service.dart' as _i2;
import 'package:au_bio_jardin_app/services/user_service.dart' as _i3;
import 'package:flutter/material.dart' as _i8;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserService_1 extends _i1.SmartFake implements _i3.UserService {
  _FakeUserService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_2 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_3 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_4 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_5 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_6 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_7 extends _i1.SmartFake implements _i4.AppleOptions {
  _FakeAppleOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i5.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_0(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i2.AuthService);

  @override
  _i3.UserService get userService =>
      (super.noSuchMethod(
            Invocation.getter(#userService),
            returnValue: _FakeUserService_1(
              this,
              Invocation.getter(#userService),
            ),
          )
          as _i3.UserService);

  @override
  _i6.Future<_i7.UserModel?> signUp({
    required _i8.BuildContext? context,
    required _i7.UserModel? user,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #context: context,
              #user: user,
              #password: password,
            }),
            returnValue: _i6.Future<_i7.UserModel?>.value(),
          )
          as _i6.Future<_i7.UserModel?>);

  @override
  _i6.Future<bool> updateUserProfile({
    required _i8.BuildContext? context,
    required _i7.UserModel? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #context: context,
              #user: user,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i7.UserModel?> signInExistingAccount({
    required _i8.BuildContext? context,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInExistingAccount, [], {
              #context: context,
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<_i7.UserModel?>.value(),
          )
          as _i6.Future<_i7.UserModel?>);

  @override
  _i6.Future<void> signOut(_i8.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.UserModel?> fetchUserProfile(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [email]),
            returnValue: _i6.Future<_i7.UserModel?>.value(),
          )
          as _i6.Future<_i7.UserModel?>);

  @override
  _i6.Stream<List<_i7.UserModel>> getGardenersStream() =>
      (super.noSuchMethod(
            Invocation.method(#getGardenersStream, []),
            returnValue: _i6.Stream<List<_i7.UserModel>>.empty(),
          )
          as _i6.Stream<List<_i7.UserModel>>);

  @override
  _i6.Stream<List<_i7.UserModel>> getCustomersStream() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersStream, []),
            returnValue: _i6.Stream<List<_i7.UserModel>>.empty(),
          )
          as _i6.Stream<List<_i7.UserModel>>);

  @override
  _i6.Future<List<_i7.UserModel>> searchCustomersByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#searchCustomersByName, [name]),
            returnValue: _i6.Future<List<_i7.UserModel>>.value(
              <_i7.UserModel>[],
            ),
          )
          as _i6.Future<List<_i7.UserModel>>);

  @override
  void showErrorSnack(_i8.BuildContext? context, String? message) =>
      super.noSuchMethod(
        Invocation.method(#showErrorSnack, [context, message]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> disableUserAccount(
    _i8.BuildContext? context,
    _i7.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#disableUserAccount, [context, user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enableUserAccount(
    _i8.BuildContext? context,
    _i7.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enableUserAccount, [context, user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_2(this, Invocation.getter(#iOptions)),
          )
          as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_3(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_4(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_5(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_6(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i4.WebOptions);

  @override
  _i4.AppleOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeAppleOptions_7(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i4.AppleOptions);

  @override
  Map<String, List<_i8.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
            Invocation.getter(#getListeners),
            returnValue: <String, List<_i8.ValueChanged<String?>>>{},
          )
          as Map<String, List<_i8.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> write({
    required String? key,
    required String? value,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> read({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> containsKey({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> delete({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String>> readAll({
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> deleteAll({
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);
}
