// Mocks generated by Mockito 5.4.6 from annotations
// in au_bio_jardin_app/test/viewmodels/cart_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:au_bio_jardin_app/models/delivery_method_config.dart' as _i14;
import 'package:au_bio_jardin_app/models/order_item.dart' as _i15;
import 'package:au_bio_jardin_app/models/order_model.dart' as _i5;
import 'package:au_bio_jardin_app/models/user_model.dart' as _i3;
import 'package:au_bio_jardin_app/models/weekly_offer.dart' as _i12;
import 'package:au_bio_jardin_app/repositories/account_repository.dart' as _i2;
import 'package:au_bio_jardin_app/repositories/order_repository.dart' as _i13;
import 'package:au_bio_jardin_app/services/order_service.dart' as _i4;
import 'package:au_bio_jardin_app/viewmodels/account_view_model.dart' as _i6;
import 'package:au_bio_jardin_app/viewmodels/weekly_offers_view_model.dart'
    as _i11;
import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountRepository_0 extends _i1.SmartFake
    implements _i2.AccountRepository {
  _FakeAccountRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderService_2 extends _i1.SmartFake implements _i4.OrderService {
  _FakeOrderService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderModel_3 extends _i1.SmartFake implements _i5.OrderModel {
  _FakeOrderModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountViewModel extends _i1.Mock implements _i6.AccountViewModel {
  MockAccountViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountRepository get accountRepository =>
      (super.noSuchMethod(
            Invocation.getter(#accountRepository),
            returnValue: _FakeAccountRepository_0(
              this,
              Invocation.getter(#accountRepository),
            ),
          )
          as _i2.AccountRepository);

  @override
  _i3.UserModel get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeUserModel_1(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i3.UserModel);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get confirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmPassword),
            ),
          )
          as String);

  @override
  bool get showSignInForm =>
      (super.noSuchMethod(
            Invocation.getter(#showSignInForm),
            returnValue: false,
          )
          as bool);

  @override
  bool get showSignUpForm =>
      (super.noSuchMethod(
            Invocation.getter(#showSignUpForm),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Stream<List<_i3.UserModel>> get gardenersStream =>
      (super.noSuchMethod(
            Invocation.getter(#gardenersStream),
            returnValue: _i8.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i8.Stream<List<_i3.UserModel>>);

  @override
  _i8.Stream<List<_i3.UserModel>> get customersStream =>
      (super.noSuchMethod(
            Invocation.getter(#customersStream),
            returnValue: _i8.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i8.Stream<List<_i3.UserModel>>);

  @override
  set currentUser(_i3.UserModel? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set password(String? value) => super.noSuchMethod(
    Invocation.setter(#password, value),
    returnValueForMissingStub: null,
  );

  @override
  set confirmPassword(String? value) => super.noSuchMethod(
    Invocation.setter(#confirmPassword, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignInForm(bool? value) => super.noSuchMethod(
    Invocation.setter(#showSignInForm, value),
    returnValueForMissingStub: null,
  );

  @override
  set showSignUpForm(bool? value) => super.noSuchMethod(
    Invocation.setter(#showSignUpForm, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleSignInForm() => super.noSuchMethod(
    Invocation.method(#toggleSignInForm, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSignUpForm() => super.noSuchMethod(
    Invocation.method(#toggleSignUpForm, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signOut(_i9.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [context]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearUserData() => super.noSuchMethod(
    Invocation.method(#clearUserData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> signIn(_i9.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [context]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signUp(_i9.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [context]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleGardenerStatus(
    _i9.BuildContext? context,
    _i3.UserModel? user,
    bool? isGardener,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleGardenerStatus, [
              context,
              user,
              isGardener,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.UserModel>> searchCustomers(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#searchCustomers, [name]),
            returnValue: _i8.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i8.Future<List<_i3.UserModel>>);

  @override
  _i8.Future<void> promoteToGardener(
    _i9.BuildContext? context,
    _i3.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#promoteToGardener, [context, user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> updateUserProfile(
    _i9.BuildContext? context,
    _i3.UserModel? updatedUser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [context, updatedUser]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disableCustomerAccount(
    _i9.BuildContext? context,
    _i3.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#disableCustomerAccount, [context, user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> enableCustomerAccount(
    _i9.BuildContext? context,
    _i3.UserModel? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enableCustomerAccount, [context, user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isPasswordValid(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#isPasswordValid, [password]),
            returnValue: false,
          )
          as bool);

  @override
  bool isEmailValid(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailValid, [email]),
            returnValue: false,
          )
          as bool);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WeeklyOffersViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeeklyOffersViewModel extends _i1.Mock
    implements _i11.WeeklyOffersViewModel {
  MockWeeklyOffersViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPublishing =>
      (super.noSuchMethod(Invocation.getter(#isPublishing), returnValue: false)
          as bool);

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  List<_i12.WeeklyOffer> get offers =>
      (super.noSuchMethod(
            Invocation.getter(#offers),
            returnValue: <_i12.WeeklyOffer>[],
          )
          as List<_i12.WeeklyOffer>);

  @override
  _i11.OfferFilter get offerFilter =>
      (super.noSuchMethod(
            Invocation.getter(#offerFilter),
            returnValue: _i11.OfferFilter.all,
          )
          as _i11.OfferFilter);

  @override
  set isPublishing(bool? value) => super.noSuchMethod(
    Invocation.setter(#isPublishing, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelSubscriptions() => super.noSuchMethod(
    Invocation.method(#cancelSubscriptions, []),
    returnValueForMissingStub: null,
  );

  @override
  void safeNotifyListeners() => super.noSuchMethod(
    Invocation.method(#safeNotifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void setOfferFilter(_i11.OfferFilter? filter) => super.noSuchMethod(
    Invocation.method(#setOfferFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> createOffer(_i12.WeeklyOffer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [offer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateOffer(_i12.WeeklyOffer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#updateOffer, [offer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> duplicateOffer(
    _i12.WeeklyOffer? source,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateOffer, [source, start, end]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> publishOffer(
    _i12.WeeklyOffer? offer,
    _i9.BuildContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#publishOffer, [offer, context]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> closeOffer(_i12.WeeklyOffer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#closeOffer, [offer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reopenOffer(_i12.WeeklyOffer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#reopenOffer, [offer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i13.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.OrderService get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeOrderService_2(this, Invocation.getter(#service)),
          )
          as _i4.OrderService);

  @override
  _i8.Stream<List<_i5.OrderModel>> streamAllOrders({
    List<_i5.OrderStatus>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAllOrders, [], {#statuses: statuses}),
            returnValue: _i8.Stream<List<_i5.OrderModel>>.empty(),
          )
          as _i8.Stream<List<_i5.OrderModel>>);

  @override
  _i8.Future<List<_i5.OrderModel>> fetchAllOrders({
    int? limit = 20,
    _i5.OrderModel? startAfter,
    List<_i5.OrderStatus>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllOrders, [], {
              #limit: limit,
              #startAfter: startAfter,
              #statuses: statuses,
            }),
            returnValue: _i8.Future<List<_i5.OrderModel>>.value(
              <_i5.OrderModel>[],
            ),
          )
          as _i8.Future<List<_i5.OrderModel>>);

  @override
  _i8.Future<void> updateOrderStatus(
    String? orderId,
    _i5.OrderStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [orderId, status]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i5.OrderModel>> streamOrdersForCustomer(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamOrdersForCustomer, [customerId]),
            returnValue: _i8.Stream<List<_i5.OrderModel>>.empty(),
          )
          as _i8.Stream<List<_i5.OrderModel>>);

  @override
  _i8.Future<List<_i5.OrderModel>> fetchOrdersForCustomer({
    required String? customerId,
    int? limit = 20,
    _i5.OrderModel? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrdersForCustomer, [], {
              #customerId: customerId,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i8.Future<List<_i5.OrderModel>>.value(
              <_i5.OrderModel>[],
            ),
          )
          as _i8.Future<List<_i5.OrderModel>>);

  @override
  _i8.Future<_i5.OrderModel> createOrder({
    required String? customerId,
    required _i5.WeeklyOfferSummary? offerSummary,
    required _i14.DeliveryMethodConfig? deliveryMethod,
    List<_i15.OrderItem>? items = const [],
    _i5.OrderStatus? status = _i5.OrderStatus.pending,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #customerId: customerId,
              #offerSummary: offerSummary,
              #deliveryMethod: deliveryMethod,
              #items: items,
              #status: status,
              #notes: notes,
            }),
            returnValue: _i8.Future<_i5.OrderModel>.value(
              _FakeOrderModel_3(
                this,
                Invocation.method(#createOrder, [], {
                  #customerId: customerId,
                  #offerSummary: offerSummary,
                  #deliveryMethod: deliveryMethod,
                  #items: items,
                  #status: status,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.OrderModel>);
}
